version: '3.7'

services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      args:
        user: freshsky
        UID: 501
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005
    volumes:
      - ./:/var/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/freshsky
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=123123
      - MYSQL_USER=user
      - MYSQL_DATABASE=AuthDb
    volumes:
      - db_data:/var/lib/mysql

  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql

volumes:
  db_data: